name: Cypress E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          mkdir -p cypress/videos cypress/screenshots cypress/results

      - name: Verify TypeScript types
        run: npm run type-check

      - name: Run Cypress tests (headless)
        uses: cypress-io/github-action@v6
        with:
          # Record run to Cypress Cloud
          command: npx cypress run --browser chrome --record --tag ci --group github-run --ci-build-id ${{ github.run_id }}
          # For parallelization later (ensure >1 spec & multiple runners):
          # command: npx cypress run --browser chrome --record --parallel --tag ci --group github-shard --ci-build-id ${{ github.run_id }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: List JUnit results (debug)
        if: always()
        run: |
          echo "Listing cypress/results contents (if any)";
          ls -l cypress/results || echo "No results dir yet";
          echo "Listing videos directory";
          ls -l cypress/videos || echo "No videos dir";
          echo "Listing screenshots directory";
          ls -l cypress/screenshots || echo "No screenshots dir";

      - name: Store videos and screenshots (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/videos/**
            cypress/screenshots/**
          if-no-files-found: ignore

      - name: Upload junit results (if present)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-junit
          path: cypress/results/*.xml
          if-no-files-found: ignore
      - name: Generate Allure HTML report
        if: always()
        run: npx allure generate --clean allure-results -o allure-report || echo "Allure generate failed"
      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/**
          if-no-files-found: ignore
      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/**
          if-no-files-found: ignore
      - name: Clean up Allure results before deployment
        run: |
                  find ./allure-report -type f -size +100M -exec rm -f {} \;  # Remove large files over 100MB
      # 6. Deploy Allure Report to GitHub Pages
      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          keep_files: false # Prevents large history accumulation
          force_orphan: true  # Ensures a clean commit without history
